-- TABELA DE AGENDAMENTOS

create table if not exists public.bookings (

  id bigint
    generated by default as identity
    primary key,

  name text not null,

  service text not null,

  price numeric(10, 2) not null,

  date date not null,

  time time not null,

  status text
    not null
    default 'pending'
    check (
      status in (
        'pending',
        'confirmed',
        'cancelled',
        'expired'
      )
    ),

  expires_at timestamptz
    not null
    default (
      now() + interval '30 minutes'
    ),

  created_at timestamptz
    not null
    default now(),

  confirmed_at timestamptz

);


-- IMPEDIR DOIS AGENDAMENTOS ATIVOS
-- NO MESMO DIA E HORÁRIO

create unique index
if not exists bookings_active_time_unique

on public.bookings (
  date,
  time
)

where status in (
  'pending',
  'confirmed'
);


-- ATIVAR SEGURANÇA DA TABELA

alter table public.bookings
enable row level security;


-- CLIENTES NÃO PODEM ACESSAR
-- DIRETAMENTE A TABELA

revoke all
on public.bookings
from anon;


-- USUÁRIO AUTENTICADO PODE
-- CONSULTAR E ATUALIZAR

grant select, update
on public.bookings
to authenticated;


-- REMOVER POLÍTICAS ANTERIORES

drop policy
if exists "administrador visualiza reservas"
on public.bookings;

drop policy
if exists "administrador atualiza reservas"
on public.bookings;


-- POLÍTICA PARA VISUALIZAR

create policy
"administrador visualiza reservas"

on public.bookings

for select

to authenticated

using (true);


-- POLÍTICA PARA ATUALIZAR

create policy
"administrador atualiza reservas"

on public.bookings

for update

to authenticated

using (true)

with check (true);


-- FUNÇÃO PARA CONSULTAR
-- HORÁRIOS INDISPONÍVEIS

create or replace function
public.unavailable_times(
  p_date date
)

returns table (
  time time,
  status text
)

language plpgsql

security definer

set search_path = public

as $$

begin

  -- EXPIRAR SOLICITAÇÕES ANTIGAS

  update public.bookings

  set status = 'expired'

  where status = 'pending'

  and expires_at <= now();


  -- RETORNAR HORÁRIOS BLOQUEADOS

  return query

  select
    booking.time,
    booking.status

  from public.bookings as booking

  where booking.date = p_date

  and booking.status in (
    'pending',
    'confirmed'
  )

  and (
    booking.status = 'confirmed'

    or booking.expires_at > now()
  );

end;

$$;


-- FUNÇÃO PARA CLIENTE
-- SOLICITAR UM AGENDAMENTO

create or replace function
public.request_booking(

  p_name text,

  p_service text,

  p_price numeric,

  p_date date,

  p_time time

)

returns bigint

language plpgsql

security definer

set search_path = public

as $$

declare

  new_booking_id bigint;

begin

  -- VALIDAR NOME

  if length(trim(p_name)) < 2 then

    raise exception
      'Informe um nome válido';

  end if;


  -- NÃO PERMITIR DATA PASSADA

  if p_date < current_date then

    raise exception
      'A data escolhida já passou';

  end if;


  -- EXPIRAR SOLICITAÇÕES ANTIGAS

  update public.bookings

  set status = 'expired'

  where status = 'pending'

  and expires_at <= now();


  -- CRIAR SOLICITAÇÃO

  insert into public.bookings (

    name,

    service,

    price,

    date,

    time,

    status,

    expires_at

  )

  values (

    trim(p_name),

    p_service,

    p_price,

    p_date,

    p_time,

    'pending',

    now() + interval '30 minutes'

  )

  returning id
  into new_booking_id;


  return new_booking_id;


exception

  when unique_violation then

    raise exception
      'Horário indisponível';

end;

$$;


-- PROTEGER AS FUNÇÕES

revoke all

on function public.request_booking(
  text,
  text,
  numeric,
  date,
  time
)

from public;


revoke all

on function public.unavailable_times(
  date
)

from public;


-- CLIENTE PODE SOLICITAR HORÁRIO

grant execute

on function public.request_booking(
  text,
  text,
  numeric,
  date,
  time
)

to anon;


-- CLIENTE E ADMINISTRADOR PODEM
-- CONSULTAR HORÁRIOS INDISPONÍVEIS

grant execute

on function public.unavailable_times(
  date
)

to anon, authenticated;